services:
  graphhopper:
    build: .
    restart: unless-stopped
    container_name: graphhopper
    ports:
      - "8989:8989"
      - "8990:8990"
    volumes:
      - ./data:/data
    environment:
      - OSM_FILE=Regensburg.osm.pbf